# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import proto.qkd_pb2 as qkd__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in qkd_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KeyManagerStub(object):
    """gRPC service definition for the KeyManager (KMS)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OpenConnect = channel.unary_unary(
                '/qkd.KeyManager/OpenConnect',
                request_serializer=qkd__pb2.OpenConnectRequest.SerializeToString,
                response_deserializer=qkd__pb2.OpenConnectResponse.FromString,
                _registered_method=True)
        self.GetKey = channel.unary_unary(
                '/qkd.KeyManager/GetKey',
                request_serializer=qkd__pb2.GetKeyRequest.SerializeToString,
                response_deserializer=qkd__pb2.GetKeyResponse.FromString,
                _registered_method=True)
        self.CloseConnection = channel.unary_unary(
                '/qkd.KeyManager/CloseConnection',
                request_serializer=qkd__pb2.CloseConnectionRequest.SerializeToString,
                response_deserializer=qkd__pb2.CloseConnectionResponse.FromString,
                _registered_method=True)


class KeyManagerServicer(object):
    """gRPC service definition for the KeyManager (KMS)
    """

    def OpenConnect(self, request, context):
        """Opens a connection between the client (APP) and the KMS
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetKey(self, request, context):
        """Retrieves a key from the KMS for a given KSID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseConnection(self, request, context):
        """Closes the connection for a given KSID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KeyManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OpenConnect': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenConnect,
                    request_deserializer=qkd__pb2.OpenConnectRequest.FromString,
                    response_serializer=qkd__pb2.OpenConnectResponse.SerializeToString,
            ),
            'GetKey': grpc.unary_unary_rpc_method_handler(
                    servicer.GetKey,
                    request_deserializer=qkd__pb2.GetKeyRequest.FromString,
                    response_serializer=qkd__pb2.GetKeyResponse.SerializeToString,
            ),
            'CloseConnection': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseConnection,
                    request_deserializer=qkd__pb2.CloseConnectionRequest.FromString,
                    response_serializer=qkd__pb2.CloseConnectionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'qkd.KeyManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('qkd.KeyManager', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KeyManager(object):
    """gRPC service definition for the KeyManager (KMS)
    """

    @staticmethod
    def OpenConnect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qkd.KeyManager/OpenConnect',
            qkd__pb2.OpenConnectRequest.SerializeToString,
            qkd__pb2.OpenConnectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qkd.KeyManager/GetKey',
            qkd__pb2.GetKeyRequest.SerializeToString,
            qkd__pb2.GetKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseConnection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qkd.KeyManager/CloseConnection',
            qkd__pb2.CloseConnectionRequest.SerializeToString,
            qkd__pb2.CloseConnectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
